apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx #refers to a Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
